ECS:
  ip: 121.41.93.88

spring:
  ###数据库连接配置信息###
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ECS.ip}:3306/mlive_cosid
    username: root
    password: root

  ###nacos注册地址###
  application:
    name: max-live-id-generate-provider
  cloud:
    nacos:
          discovery:
            namespace: max-live
            server-addr: ${ECS.ip}:8848

###dubbo服务注册地址###
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://${ECS.ip}:8848?namespace=max-live
    id: nacos-registry
  protocol:
    name: dubbo
    port: -1

cosid:
  snowflake:
    enabled: true #是否启用雪花算法，默认为true
    provider:
      snowId:
        sequence-reset-threshold: 10
        clock-sync: true
    share:
      enabled: false
  machine:
    distributor:
      type: jdbc
    enabled: true

  segment:
    share:
      enabled: false
    provider:
      sequ:
        offset: 10
        step: 1
    enabled: true
    distributor:
      type: jdbc
      jdbc:
        enable-auto-init-cosid-table: true
    mode: chain
    chain:
      safe-distributor: 10


