server:
  port: 80

ECS:
  ip: 121.41.93.88

spring:
  application:
    name: max-live-gateway
  cloud:
    nacos:
      discovery:
        namespace: max-live
        server-addr: ${ECS.ip}:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : max-live-api
          uri: lb://max-live-api
          predicates:
            - Path=/user/**
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins:
#            - "*"
#            allowedMethods:
#              - "GET"
#              - "POST"
#              - "PUT"
#              - "DELETE"
#              - "OPTIONS"
#            allowedHeaders: '*'
#            allowCredentials: false
#            max-age: 36000



#dubbo服务注册地址
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://${ECS.ip}:8848?namespace=max-live
    id: nacos-registry
  protocol:
    name: dubbo
    port: -1

max-live:
  gateway:
    white-url-list:
      - /user/mobileLogin
      - /user/sendmSMS
      - /user/sendBin
